import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { gql, useQuery } from "@apollo/client";
import { useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { statusColor, textColor } from "@/utilis/color";

const GET_POKE = gql`
  query GetPokemon($count: Int!) {
    pokemons(first: $count) {
      id
      number
      name
      image
      types
    }
  }
`;

export default function Home() {
  const [count, setCount] = useState(20);

  const { loading, error, data } = useQuery(GET_POKE, {
    variables: { count },
  });

  if (loading) {
    return (
      <article
        style={{
          height: "100vh",
          margin: 0,
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <section className="pokemon"></section>
      </article>
    );
  }

  if (error) {
    return (
      <h2
        style={{
          height: "100vh",
          margin: 0,
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        Error Page
      </h2>
    );
  }

  if (data?.pokemons) {
    return (
      <section style={{ textAlign: "center" }}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          {data.pokemons.map((arr, i) => (
            <Link href={`/pokemons/${arr.id}&${arr.name}`} key={i}>
              <section className={styles.section}>
                <figure>
                  <Image
                    src={arr.image}
                    alt="No Image"
                    width={200}
                    height={200}
                  />
                  <figcaption
                    style={{ textAlign: "initial", color: "#919191" }}
                  >
                    #{arr.number}
                  </figcaption>
                </figure>
                <h3>{arr.name}</h3>
                <section style={{ display: "flex", gap: 12, flexWrap: "wrap" }}>
                  {arr.types.map((arr, i) => {
                    return (
                      <article
                        style={{
                          background: statusColor[arr],
                          padding: "4px 1.5rem",
                          borderRadius: 5,
                          color: textColor[arr],
                        }}
                        key={i}
                      >
                        {arr}
                      </article>
                    );
                  })}
                </section>
              </section>
            </Link>
          ))}
        </main>
        <button
          style={{
            backgroundColor: "#30a7d7",
            border: "none",
            padding: "1rem 4rem",
            fontSize: "1.5rem",
            color: "#fff",
            marginBottom: "4rem",
            cursor: "pointer",
          }}
          onClick={() => {
            setCount(count + 20);
          }}
        >
          Load more Pokemons
        </button>
      </section>
    );
  }
}
